name: skorch
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - zlib=1.2.11
  - sphinxcontrib-serializinghtml=1.1.4
  - mkl-service=2.3.0
  - click=7.1.2
  - importlib-metadata=3.10.0
  - tensorboard[version='>=1.14.0']
  - google-auth-oauthlib=0.4.2
  - libgcc-ng=9.1.0
  - sqlite=3.35.4
  - ca-certificates
  - lazy-object-proxy=1.6.0
  - pytorch=1.8.1
  - packaging=20.9
  - babel=2.9.0
  - python=3.9.4
  - pyjwt=2.0.1
  - chardet=3.0.4
  - numpydoc
  - certifi
  - blinker=1.4
  - tensorboard-plugin-wit=1.6.0
  - astroid=2.5
  - attrs=20.3.0
  - threadpoolctl=2.1.0
  - google-auth=1.28.1
  - tzdata=2020f
  - libstdcxx-ng=9.1.0
  - scipy=1.6.2
  - wrapt=1.12.1
  - absl-py=0.12.0
  - more-itertools=8.7.0
  - intel-openmp=2020.2
  - libgfortran-ng=7.3.0
  - werkzeug=1.0.1
  - numpy-base=1.19.2
  - imagesize=1.2.0
  - wheel=0.36.2
  - scikit-learn=0.24.1
  - pluggy=0.13.1
  - typing-extensions=3.7.4.3
  - aiohttp=3.7.4
  - pyasn1-modules=0.2.8
  - sphinxcontrib-htmlhelp=1.0.3
  - yarl=1.6.3
  - _libgcc_mutex=0.1
  - rsa=4.7.2
  - protobuf=3.14.0
  - c-ares=1.17.1
  - tqdm=4.59.0
  - docutils=0.17
  - tabulate=0.8.9
  - cryptography=2.9.2
  - idna=2.10
  - oauthlib=3.1.0
  - alabaster=0.7.12
  - zipp=3.4.1
  - ninja=1.10.2
  - sphinxcontrib-qthelp=1.0.3
  - pytest-cov
  - blas=1.0
  - isort=5.8.0
  - jinja2=2.11.3
  - markupsafe=1.1.1
  - cachetools=4.2.1
  - python-dateutil=2.8.1
  - colorama=0.4.4
  - libuv=1.40.0
  - sphinxcontrib-applehelp=1.0.2
  - pyasn1=0.4.8
  - toml=0.10.2
  - pyopenssl=20.0.1
  - requests-oauthlib=1.3.0
  - async-timeout=3.0.1
  - flaky
  - pycparser=2.20
  - multidict=5.1.0
  - libffi=3.3
  - snowballstemmer=2.1.0
  - pytz=2021.1
  - cffi=1.14.5
  - mccabe=0.6.1
  - grpcio=1.36.1
  - openssl
  - six=1.15.0
  - setuptools=52.0.0
  - numpy=1.19.2
  - ld_impl_linux-64=2.33.1
  - requests=2.25.1
  - iniconfig=1.1.1
  - pysocks=1.7.1
  - pylint
  - urllib3=1.26.4
  - coverage=5.5
  - cudatoolkit=10.2.89
  - pip=21.0.1
  - pyparsing=2.4.7
  - markdown=3.3.4
  - pytest[version='>=3.4']
  - sphinxcontrib-jsmath=1.0.1
  - readline=8.1
  - tk=8.6.10
  - pygments=2.8.1
  - cython=0.29.23
  - ncurses=6.2
  - mkl_random=1.0.2
  - brotlipy=0.7.0
  - pandas
  - libprotobuf=3.14.0
  - mkl_fft=1.3.0
  - xz=5.2.5
  - mkl=2020.2
  - py=1.10.0
  - typing_extensions=3.7.4.3
  - joblib=1.0.1
  - sphinx
  - sphinxcontrib-devhelp=1.0.2
  - neptune-client[version='>=0.4.103']
  - pillow
  - fire
  - openpyxl
  - sphinx_rtd_theme
  - wandb[version='>=0.8.30']
  - future[version='>=0.17.1']
  - matplotlib[version='>=2.0.2']
  - jupyter
  - pip:
    - sacred==0.8.2
