name: build

# Build on every branch every push and pull request change.
on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  build:
    name: test Python source code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install          

      - name: Run pylint
        run: poetry run pylint --fail-under=8
 